---
name: container-release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=version::${GITHUB_REF##*/}

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2.9
        with:
         image: kutara-ostree
         tags: v${{ steps.prep.outputs.version }} latest
         oci: true
         archs: amd64, arm64
         layers: true
         containerfiles: ./Dockerfile
        
      - name: Push
        uses: redhat-actions/push-to-registry@v2.7.1
        with:
         image: ${{ steps.build.outputs.image }}
         tags:  ${{ steps.build.outputs.tags }}
         registry: ghcr.io/${{ github.actor }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
